export interface PopularService {
  name: string;
  url: string;
  domain: string;
  price: number;
  currency: "EUR" | "USD";
  billing_cycle: "monthly" | "yearly";
  category: string;
  emoji: string;
  description: string;
}

export const POPULAR_SERVICES: PopularService[] = [
  // ── Streaming ──────────────────────────────────────────────────────────────
  {
    name: "Netflix",
    url: "https://www.netflix.com",
    domain: "netflix.com",
    price: 17.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "🎬",
    description: "Plan Estándar con anuncios",
  },
  {
    name: "HBO Max",
    url: "https://www.max.com",
    domain: "max.com",
    price: 8.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "📺",
    description: "Series y películas HBO",
  },
  {
    name: "Amazon Prime Video",
    url: "https://www.primevideo.com",
    domain: "primevideo.com",
    price: 4.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "📦",
    description: "Incluido con Amazon Prime",
  },
  {
    name: "Disney+",
    url: "https://www.disneyplus.com",
    domain: "disneyplus.com",
    price: 11.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "🏰",
    description: "Disney, Marvel, Star Wars, Pixar",
  },
  {
    name: "Apple TV+",
    url: "https://tv.apple.com",
    domain: "tv.apple.com",
    price: 9.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "🍎",
    description: "Series y películas originales Apple",
  },
  {
    name: "YouTube Premium",
    url: "https://www.youtube.com",
    domain: "youtube.com",
    price: 13.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "▶️",
    description: "Sin anuncios + YouTube Music",
  },
  {
    name: "Crunchyroll",
    url: "https://www.crunchyroll.com",
    domain: "crunchyroll.com",
    price: 7.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "⛩️",
    description: "Anime en streaming",
  },
  {
    name: "Movistar+",
    url: "https://ver.movistarplus.es",
    domain: "movistarplus.es",
    price: 14.00,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Streaming",
    emoji: "📡",
    description: "Plataforma de Telefónica",
  },

  // ── Música ─────────────────────────────────────────────────────────────────
  {
    name: "Spotify",
    url: "https://www.spotify.com",
    domain: "spotify.com",
    price: 11.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Música",
    emoji: "🎵",
    description: "Música en streaming",
  },
  {
    name: "Apple Music",
    url: "https://music.apple.com",
    domain: "music.apple.com",
    price: 10.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Música",
    emoji: "🎶",
    description: "Música de Apple",
  },
  {
    name: "Tidal",
    url: "https://tidal.com",
    domain: "tidal.com",
    price: 9.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Música",
    emoji: "🌊",
    description: "Música HiFi y sin pérdidas",
  },

  // ── Gaming ─────────────────────────────────────────────────────────────────
  {
    name: "PlayStation Plus",
    url: "https://www.playstation.com",
    domain: "playstation.com",
    price: 8.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Gaming",
    emoji: "🎮",
    description: "Juegos online + catálogo PS",
  },
  {
    name: "Xbox Game Pass",
    url: "https://www.xbox.com/game-pass",
    domain: "xbox.com",
    price: 14.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Gaming",
    emoji: "🟢",
    description: "Catálogo de juegos Xbox + PC",
  },
  {
    name: "Nintendo Switch Online",
    url: "https://www.nintendo.com",
    domain: "nintendo.com",
    price: 3.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Gaming",
    emoji: "🕹️",
    description: "Juegos online Nintendo",
  },
  {
    name: "EA Play",
    url: "https://www.ea.com/ea-play",
    domain: "ea.com",
    price: 4.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Gaming",
    emoji: "🏆",
    description: "Catálogo EA + acceso anticipado",
  },

  // ── IA ─────────────────────────────────────────────────────────────────────
  {
    name: "ChatGPT Plus",
    url: "https://chatgpt.com",
    domain: "chatgpt.com",
    price: 20.00,
    currency: "USD",
    billing_cycle: "monthly",
    category: "Software",
    emoji: "🤖",
    description: "GPT-4o + acceso prioritario",
  },
  {
    name: "Claude Pro",
    url: "https://claude.ai",
    domain: "claude.ai",
    price: 20.00,
    currency: "USD",
    billing_cycle: "monthly",
    category: "Software",
    emoji: "🧠",
    description: "Claude Sonnet + Opus ilimitado",
  },
  {
    name: "Midjourney",
    url: "https://www.midjourney.com",
    domain: "midjourney.com",
    price: 10.00,
    currency: "USD",
    billing_cycle: "monthly",
    category: "Software",
    emoji: "🎨",
    description: "Generación de imágenes con IA",
  },
  {
    name: "Perplexity Pro",
    url: "https://www.perplexity.ai",
    domain: "perplexity.ai",
    price: 20.00,
    currency: "USD",
    billing_cycle: "monthly",
    category: "Software",
    emoji: "🔍",
    description: "Buscador con IA avanzada",
  },

  // ── Productividad ──────────────────────────────────────────────────────────
  {
    name: "Notion",
    url: "https://www.notion.so",
    domain: "notion.so",
    price: 10.00,
    currency: "USD",
    billing_cycle: "monthly",
    category: "Productividad",
    emoji: "📝",
    description: "Notas, bases de datos, wikis",
  },
  {
    name: "Microsoft 365",
    url: "https://www.microsoft.com/microsoft-365",
    domain: "microsoft.com",
    price: 7.00,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Productividad",
    emoji: "💼",
    description: "Office + 1TB OneDrive",
  },
  {
    name: "Adobe Creative Cloud",
    url: "https://www.adobe.com",
    domain: "adobe.com",
    price: 59.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Software",
    emoji: "🎭",
    description: "Photoshop, Illustrator, Premiere…",
  },

  // ── Nube ───────────────────────────────────────────────────────────────────
  {
    name: "iCloud+",
    url: "https://www.icloud.com",
    domain: "icloud.com",
    price: 0.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Nube",
    emoji: "☁️",
    description: "50 GB almacenamiento Apple",
  },
  {
    name: "Google One",
    url: "https://one.google.com",
    domain: "one.google.com",
    price: 1.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Nube",
    emoji: "🔵",
    description: "100 GB almacenamiento Google",
  },
  {
    name: "Dropbox Plus",
    url: "https://www.dropbox.com",
    domain: "dropbox.com",
    price: 11.99,
    currency: "EUR",
    billing_cycle: "monthly",
    category: "Nube",
    emoji: "📂",
    description: "2 TB almacenamiento en nube",
  },
];

export const SERVICE_CATEGORIES = [
  "Todos",
  "Streaming",
  "Música",
  "Gaming",
  "Software",
  "Productividad",
  "Nube",
] as const;
